export const NotificationTypes = {
    BUDGET_LIMIT_WARNING: "BUDGET_LIMIT_WARNING",
    BUDGET_LIMIT_EXCEEDED: "BUDGET_LIMIT_EXCEEDED",

    BUDGET_LIMIT_CREATED: "BUDGET_LIMIT_CREATED",
    BUDGET_LIMIT_UPDATED: "BUDGET_LIMIT_UPDATED",
    BUDGET_LIMIT_DELETED: "BUDGET_LIMIT_DELETED",

    TRANSACTION_CREATED: "TRANSACTION_CREATED",
    TRANSACTION_UPDATED: "TRANSACTION_UPDATED",
    TRANSACTION_DELETED: "TRANSACTION_DELETED",


    WORKSPACE_INVITATION_RECEIVED: "WORKSPACE_INVITATION_RECEIVED",


    WORKSPACE_MEMBER_JOINED: "WORKSPACE_MEMBER_JOINED",
    WORKSPACE_MEMBER_REMOVED: "WORKSPACE_MEMBER_REMOVED",
    WORKSPACE_MEMBER_ROLE_UPDATED: "WORKSPACE_MEMBER_ROLE_UPDATED",
    WORKSPACE_MEMBER_LEFT: "WORKSPACE_MEMBER_LEFT",

    WORKSPACE_INVITATION_CREATED: "WORKSPACE_INVITATION_CREATED",
    WORKSPACE_INVITATION_ACCEPTED: "WORKSPACE_INVITATION_ACCEPTED",
    WORKSPACE_INVITATION_REJECTED: "WORKSPACE_INVITATION_REJECTED",

    MONTHLY_BUDGET_SUMMARY: "MONTHLY_BUDGET_SUMMARY",
} as const;

export type NotificationType =
    (typeof NotificationTypes)[keyof typeof NotificationTypes];

export type CreateNotificationInput = {
    userId: string;
    workspaceId?: string;
    type: NotificationType;

    titleKey: string;
    messageKey: string;
    messageParams?: Record<string, unknown>;

    metadata?: Record<string, unknown>;
    expiresAt?: Date;
    dedupeKey?: string;
};